from __future__ import annotations


def list_source_templates() -> list[dict]:
    return [
        {
            "mode": "pumpfun",
            "label": "Pump.fun launchpad",
            "description": "Use the dedicated Pump.fun collector for Solana launches.",
            "example": {
                "name": "pump-fun",
                "chain": "solana",
                "enabled": True,
                "mode": "pumpfun",
                "url": "https://pump.fun/",
            },
        },
        {
            "mode": "fourmeme",
            "label": "Four.meme launchpad",
            "description": "BSC launchpad preset using the Four.meme sitemap collector.",
            "example": {
                "name": "four-meme",
                "chain": "bsc",
                "enabled": True,
                "mode": "fourmeme",
                "url": "https://four.meme",
                "limit": 50,
            },
        },
        {
            "mode": "sitemap",
            "label": "Solana homepage crawler",
            "description": "Website crawler preset for Solana project homepages and launch sites.",
            "example": {
                "name": "solana-homepages",
                "chain": "solana",
                "enabled": True,
                "mode": "sitemap",
                "url": "https://example.com",
                "limit": 25,
            },
        },
        {
            "mode": "sitemap",
            "label": "BSC homepage crawler",
            "description": "Website crawler preset for BSC project homepages and launch sites.",
            "example": {
                "name": "bsc-homepages",
                "chain": "bsc",
                "enabled": True,
                "mode": "sitemap",
                "url": "https://example.com",
                "limit": 25,
            },
        },
        {
            "mode": "rss",
            "label": "RSS feed",
            "description": "Announcement feeds that publish project launches in RSS 2.0 format.",
            "example": {
                "name": "news-feed",
                "chain": "solana",
                "enabled": True,
                "mode": "rss",
                "url": "https://example.com/feed.xml",
            },
        },
        {
            "mode": "rss",
            "label": "RSS feed (BSC)",
            "description": "A BSC announcement feed that can be monitored as a launch source.",
            "example": {
                "name": "bsc-news-feed",
                "chain": "bsc",
                "enabled": True,
                "mode": "rss",
                "url": "https://example.com/bsc-feed.xml",
            },
        },
        {
            "mode": "atom",
            "label": "Atom feed",
            "description": "Announcement feeds that publish project launches in Atom format.",
            "example": {
                "name": "atom-feed",
                "chain": "bsc",
                "enabled": True,
                "mode": "atom",
                "url": "https://example.com/feed.atom",
            },
        },
        {
            "mode": "json",
            "label": "JSON feed",
            "description": "Structured feeds exposing launch items in JSON.",
            "example": {
                "name": "json-feed",
                "chain": "solana",
                "enabled": True,
                "mode": "json",
                "url": "https://example.com/feed.json",
                "items_path": "items",
            },
        },
        {
            "mode": "json",
            "label": "JSON feed (BSC)",
            "description": "A JSON launch feed preset for BSC projects.",
            "example": {
                "name": "bsc-json-feed",
                "chain": "bsc",
                "enabled": True,
                "mode": "json",
                "url": "https://example.com/bsc-feed.json",
                "items_path": "items",
            },
        },
        {
            "mode": "html",
            "label": "HTML listing",
            "description": "Project directories or listing pages with data-project attributes.",
            "example": {
                "name": "listing",
                "chain": "bsc",
                "enabled": True,
                "mode": "html",
                "url": "https://example.com/list",
            },
        },
        {
            "mode": "sitemap",
            "label": "Sitemap crawler",
            "description": "Website root or sitemap URL. The crawler resolves robots.txt and sitemap.xml automatically.",
            "example": {
                "name": "site-crawler",
                "chain": "solana",
                "enabled": True,
                "mode": "sitemap",
                "url": "https://example.com",
                "limit": 25,
            },
        },
        {
            "mode": "research",
            "label": "Telegram research",
            "description": "Telethon-based research layer for public Telegram channels.",
            "example": {
                "name": "research-channel",
                "enabled": True,
                "mode": "research",
                "chain": "solana",
                "limit": 100,
                "channels": ["YOUR_PUBLIC_CHANNEL_USERNAME"],
            },
        },
        {
            "mode": "public",
            "label": "Telegram public channel",
            "description": "No-login collector for public Telegram channel pages at t.me/s/...",
            "example": {
                "name": "public-channel",
                "enabled": True,
                "mode": "public",
                "chain": "solana",
                "limit": 20,
                "channel": "YOUR_PUBLIC_CHANNEL_USERNAME",
            },
        },
        {
            "mode": "rss",
            "label": "Social account feed",
            "description": "Public social or announcement feeds that should be treated as social discovery inputs.",
            "example": {
                "name": "alpha-x-watch",
                "enabled": True,
                "mode": "rss",
                "chain": "solana",
                "limit": 25,
                "url": "https://example.com/feed.xml",
            },
        },
        {
            "mode": "profile",
            "label": "Social account page",
            "description": "A public profile page used to surface website, Telegram, X, or Discord links.",
            "example": {
                "name": "bsc-social-feed",
                "enabled": True,
                "mode": "profile",
                "chain": "bsc",
                "limit": 25,
                "url": "https://example.com/profile",
            },
        },
        {
            "mode": "profile",
            "label": "Pump.fun X watch",
            "description": "Track Pump.fun's public X profile as an early social signal for new Solana launches.",
            "example": {
                "name": "pumpfun-x-watch",
                "enabled": True,
                "mode": "profile",
                "chain": "solana",
                "limit": 25,
                "url": "https://x.com/pumpdotfun",
            },
        },
        {
            "mode": "profile",
            "label": "Dexscreener X watch",
            "description": "Track Dexscreener's public X profile as a market-wide early discovery signal.",
            "example": {
                "name": "dexscreener-x-watch",
                "enabled": True,
                "mode": "profile",
                "chain": "multi",
                "limit": 25,
                "url": "https://x.com/dexscreener",
            },
        },
        {
            "mode": "profile",
            "label": "Dexscreener Solana watch",
            "description": "Crawl Dexscreener Solana pair pages as an early discovery source for fresh communities and project links.",
            "example": {
                "name": "dexscreener-solana-watch",
                "enabled": True,
                "mode": "profile",
                "chain": "solana",
                "limit": 25,
                "url": "https://dexscreener.com/solana",
            },
        },
        {
            "mode": "profile",
            "label": "Dexscreener BSC watch",
            "description": "Crawl Dexscreener BSC pair pages as an early discovery source for fresh communities and project links.",
            "example": {
                "name": "dexscreener-bsc-watch",
                "enabled": True,
                "mode": "profile",
                "chain": "bsc",
                "limit": 25,
                "url": "https://dexscreener.com/bsc",
            },
        },
    ]
